default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "billetto_rails_test_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "billetto_rails_test_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD", "billetto_rails_test_production") %>